### ISSUE TITLE
remove data type from session files

### ISSUE THREAD

**Issue by sean-gall-41** [gawdSim/CbmSim#21]
Enough public opinion about including the type of a a parameter being a superfluous thing prompts me to want to remove it from the specification entirely. Thoughts?

**Comment by gawdSim** [comment]
Removed type specifier in commit [be98c65](https://github.com/gawdSim/CbmSim/commit/be98c658a8bd977dcc6ac138b0e3a14b2567d114). keeping this issue open until other dangling branches are merged and every branch reflects this change.

**Comment by gawdSim** [comment]
added this feature in.
